import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({
    btnBlue:{
        width:72,
        height:72,
        borderRadius:24,
        backgroundColor:'#345cd3',
        justifyContent:'center',
        alignItems:'center',
        margin:8,
    },
    btnDark:{
        width:72,
        height:72,
        borderRadius:24,
        backgroundColor:'#333',
        justifyContent:'center',
        alignItems:'center',
        margin:8,
    },
    btnLight:{
        width:72,
        height:72,
        borderRadius:24,
        backgroundColor:'#ededed',
        justifyContent:'center',
        alignItems:'center',
        margin:8,
    },
    btnGray:{
        width:72,
        height:72,
        borderRadius:24,
        backgroundColor:'#ccc',
        justifyContent:'center',
        alignItems:'center',
        margin:8,
    },
    smallTextLight:{
        fontSize:32,
        color:'#fff',
    },
    smallTextDark:{
        fontSize:32,
        color:'#333',
    },
    row:{
        maxWidth:'100%',
        flexDirection:'row',
    },
    viewBottom:{
        position:'absolute',
        bottom:50,
    },
    screenFirstNumber:{
        fontSize:96,
        color:'#ccc',
        fontWeight:'200',
        alignSelf:"flex-end",
    },
    screenSecondNumber:{
        fontSize:40,
        color:'#ccc',
        fontWeight:'200',
        alignSelf:'flex-end',
    }
});